import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getAnalyses, getPredictions, updateAllPendingResults } from "@/lib/predictions.functions";
import { useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, Loader2, RefreshCw } from "lucide-react";
import { PredictionCard, type Prediction } from "@/components/PredictionCard";
import { ScanScorecard } from "@/components/ScanScorecard";
import { LeagueScopeBadge } from "@/components/LeagueScopeBadge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export const Route = createFileRoute("/history")({
  head: () => ({
    meta: [
      { title: "Analysis History · BetEdge AI" },
      { name: "description", content: "Browse previous prediction scans with full reasoning, confidence trail and final-result tracking." },
      { property: "og:title", content: "Analysis History · BetEdge AI" },
      { property: "og:description", content: "Persistent record of every scan — update FT results without re-running predictions." },
      { property: "og:url", content: "/history" },
    ],
    links: [{ rel: "canonical", href: "/history" }],
  }),
  component: HistoryPage,
});

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
function formatScanLabel(iso: string): string {
  const d = new Date(iso);
  const dd = String(d.getDate()).padStart(2, "0");
  const mon = MONTHS[d.getMonth()];
  const yyyy = d.getFullYear();
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${dd} ${mon} ${yyyy} · ${hh}:${mm}`;
}

// Scanner now only generates match_winner and over_2_5_goals — the two bet types with a
// real, measurable edge in this API's data. Older scans may still have picks of the
// removed types (corners, double chance, asian handicap); "All" will still show those if
// present in history, they just won't be generated by new scans.
const TYPE_FILTERS = [
  { id: "all", label: "All" },
  { id: "match_winner", label: "Match Winner" },
  { id: "over_2_5_goals", label: "Over 2.5" },
];

const EV_FILTERS = [
  { id: "all", label: "All EV" },
  { id: "positive", label: "Positive EV" },
  { id: "negative", label: "Negative EV" },
  { id: "20plus", label: "+20% EV" },
  { id: "no_ev", label: "No EV" },
];

function matchesEvFilter(p: Prediction, evFilter: string): boolean {
  const ev = p.expected_value != null ? Number(p.expected_value) : null;
  switch (evFilter) {
    case "positive": return ev != null && ev >= 0;
    case "negative": return ev != null && ev < 0;
    case "20plus": return ev != null && ev >= 0.20;
    case "no_ev": return ev == null;
    default: return true;
  }
}

const PAGE_SIZES = [50, 100] as const;

const MONTH_NAMES = ["January","February","March","April","May","June","July","August","September","October","November","December"];

// Build "last 12 months" options as {label, from, to} — from/to are YYYY-MM-DD strings
// covering the full calendar month, computed in local time.
function buildMonthOptions() {
  const opts: { label: string; from: string; to: string }[] = [];
  const now = new Date();
  for (let i = 0; i < 12; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const y = d.getFullYear(), m = d.getMonth();
    const first = new Date(y, m, 1);
    const last = new Date(y, m + 1, 0);
    const fmt = (x: Date) => `${x.getFullYear()}-${String(x.getMonth() + 1).padStart(2, "0")}-${String(x.getDate()).padStart(2, "0")}`;
    opts.push({ label: `${MONTH_NAMES[m]} ${y}`, from: fmt(first), to: fmt(last) });
  }
  return opts;
}
const MONTH_OPTIONS = buildMonthOptions();

function HistoryPage() {
  const fa = useServerFn(getAnalyses);
  const fp = useServerFn(getPredictions);
  const updateAll = useServerFn(updateAllPendingResults);
  const qc = useQueryClient();
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState<50 | 100>(50);
  const [fromDate, setFromDate] = useState("");
  const [toDate, setToDate] = useState("");
  const [selectedMonth, setSelectedMonth] = useState(""); // empty = "All time" / custom range
  const aQ = useQuery({
    queryKey: ["analyses", page, pageSize, fromDate, toDate],
    queryFn: () => fa({ data: { page, pageSize, fromDate: fromDate || undefined, toDate: toDate || undefined } }),
  });
  const [openId, setOpenId] = useState<string | null>(null);
  const [typeFilter, setTypeFilter] = useState("all");
  const [evFilter, setEvFilter] = useState("all");

  const pickMonth = (label: string) => {
    setSelectedMonth(label);
    setPage(1);
    if (!label) { setFromDate(""); setToDate(""); return; }
    const m = MONTH_OPTIONS.find((o) => o.label === label);
    if (m) { setFromDate(m.from); setToDate(m.to); }
  };
  const changeFrom = (v: string) => { setFromDate(v); setSelectedMonth(""); setPage(1); };
  const changeTo = (v: string) => { setToDate(v); setSelectedMonth(""); setPage(1); };
  const clearDates = () => { setFromDate(""); setToDate(""); setSelectedMonth(""); setPage(1); };

  const updateMut = useMutation({
    mutationFn: () => {
      const v = typeof window !== "undefined" ? window.localStorage.getItem("betedge.apiKey") : null;
      const apiKey: 1 | 2 = v === "2" ? 2 : 1;
      return updateAll({ data: { apiKey } });
    },
    onSuccess: (r: any) => {
      const failedNote = r.failedDates ? ` (${r.failedDates} date${r.failedDates === 1 ? "" : "s"} couldn't be checked — see logs.)` : "";
      const msg = `Updated ${r.updated} result${r.updated === 1 ? "" : "s"} across ${r.dates} date${r.dates === 1 ? "" : "s"}. ${r.stillPending} match${r.stillPending === 1 ? "" : "es"} still pending.${failedNote}`;
      if (r.updated === 0) toast.warning(msg);
      else toast.success(msg);
      qc.invalidateQueries({ queryKey: ["preds"] });
    },
    onError: (e: any) => toast.error(e?.message ?? "Update failed"),
  });

  const list = aQ.data?.analyses ?? [];
  const totalPages = aQ.data?.totalPages ?? 1;
  const totalCount = aQ.data?.totalCount ?? 0;

  const changePageSize = (size: 50 | 100) => {
    setPageSize(size);
    setPage(1); // page size change resets to page 1, since offsets no longer line up
  };

  return (
    <section className="mx-auto max-w-7xl px-4 sm:px-6 py-10">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-3xl font-bold">Analysis <span className="text-neon">History</span></h1>
          <p className="text-sm text-muted-foreground mt-1">Persistent record of every scan. Update FT results without re-running predictions.</p>
        </div>
        <Button onClick={() => updateMut.mutate()} disabled={updateMut.isPending}>
          {updateMut.isPending ? <Loader2 className="animate-spin h-4 w-4" /> : <RefreshCw className="h-4 w-4" />}
          Update Results
        </Button>
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-1.5">
        {TYPE_FILTERS.map((f) => (
          <button key={f.id} onClick={() => setTypeFilter(f.id)}
            className={`px-3 h-8 rounded-md text-xs border ${typeFilter === f.id ? "bg-neon/15 border-neon/40 text-neon" : "border-border text-muted-foreground hover:text-foreground"}`}>
            {f.label}
          </button>
        ))}
        <span className="w-px h-6 bg-border mx-1" />
        {EV_FILTERS.map((f) => (
          <button key={f.id} onClick={() => setEvFilter(f.id)}
            className={`px-3 h-8 rounded-md text-xs border ${evFilter === f.id ? "bg-gold/15 border-gold/40 text-gold" : "border-border text-muted-foreground hover:text-foreground"}`}>
            {f.label}
          </button>
        ))}
        <div className="ml-auto flex items-center gap-1.5 text-xs text-muted-foreground">
          <span>Per page:</span>
          {PAGE_SIZES.map((s) => (
            <button key={s} onClick={() => changePageSize(s)}
              className={`px-2.5 h-8 rounded-md border ${pageSize === s ? "bg-neon/15 border-neon/40 text-neon" : "border-border hover:text-foreground"}`}>
              {s}
            </button>
          ))}
        </div>
      </div>

      <div className="mt-3 glass rounded-xl p-3 flex flex-wrap items-end gap-3">
        <div>
          <label className="block text-[10px] uppercase tracking-widest text-muted-foreground mb-1">Month</label>
          <select
            value={selectedMonth}
            onChange={(e) => pickMonth(e.target.value)}
            className="h-9 rounded-md bg-secondary border border-border px-2 text-sm"
          >
            <option value="">All time</option>
            {MONTH_OPTIONS.map((m) => (
              <option key={m.label} value={m.label}>{m.label}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="block text-[10px] uppercase tracking-widest text-muted-foreground mb-1">From</label>
          <input
            type="date"
            value={fromDate}
            onChange={(e) => changeFrom(e.target.value)}
            className="h-9 rounded-md bg-secondary border border-border px-2 text-sm font-mono"
          />
        </div>
        <div>
          <label className="block text-[10px] uppercase tracking-widest text-muted-foreground mb-1">To</label>
          <input
            type="date"
            value={toDate}
            onChange={(e) => changeTo(e.target.value)}
            className="h-9 rounded-md bg-secondary border border-border px-2 text-sm font-mono"
          />
        </div>
        {(fromDate || toDate || selectedMonth) && (
          <Button variant="outline" size="sm" onClick={clearDates}>Clear</Button>
        )}
      </div>

      <div className="mt-6 space-y-2">
        {aQ.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
        {!aQ.isLoading && list.length === 0 && (
          <div className="glass rounded-xl p-10 text-center text-sm text-muted-foreground">No analyses yet.</div>
        )}
        {list.map((a: any) => (
          <HistoryItem
            key={a.id}
            a={a}
            open={openId === a.id}
            onToggle={() => setOpenId((o) => (o === a.id ? null : a.id))}
            fp={fp}
            typeFilter={typeFilter}
            evFilter={evFilter}
          />
        ))}
      </div>

      {totalCount > 0 && (
        <div className="mt-6 flex items-center justify-between gap-3 flex-wrap">
          <span className="text-xs text-muted-foreground">
            Page {page} of {totalPages} · {totalCount} scan{totalCount === 1 ? "" : "s"} total
          </span>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage((p) => Math.max(1, p - 1))}>
              <ChevronLeft className="h-4 w-4" /> Previous
            </Button>
            <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => setPage((p) => Math.min(totalPages, p + 1))}>
              Next <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      )}
    </section>
  );
}

function HistoryItem({ a, open, onToggle, fp, typeFilter, evFilter }: any) {
  const q = useQuery({
    queryKey: ["preds", "analysis", a.id],
    queryFn: () => fp({ data: { analysisId: a.id } }),
    enabled: open,
  });
  const allPreds = (q.data?.predictions ?? []) as Prediction[];
  const preds = allPreds
    .filter((p) => typeFilter === "all" || p.prediction_type === typeFilter)
    .filter((p) => matchesEvFilter(p, evFilter));
  return (
    <div className="glass rounded-xl">
      <button onClick={onToggle} className="w-full flex items-center gap-3 p-4 text-left">
        {open ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
        <div className="flex-1 min-w-0">
          <div className="font-semibold">{formatScanLabel(a.created_at)}</div>
          <div className="text-xs text-muted-foreground">{a.predictions_generated} pick{a.predictions_generated === 1 ? "" : "s"} · {a.matches_analyzed} match{a.matches_analyzed === 1 ? "" : "es"} analysed</div>
        </div>
        <div className="flex items-center gap-3">
          <LeagueScopeBadge scope={a.league_scope} />
          <ScanScorecard total={a.score_total ?? a.predictions_generated ?? 0} won={a.score_won ?? 0} pending={a.score_pending ?? 0} />
          <div className="text-right">
            {a.avg_confidence != null && <div className="font-mono text-neon font-bold">{a.avg_confidence}%</div>}
          </div>
        </div>
      </button>
      {open && (
        <div className="border-t border-border p-4 space-y-4">
          <div className="text-xs text-muted-foreground">{preds.length} picks shown</div>
          {q.isLoading ? <p className="text-sm text-muted-foreground">Loading picks…</p> :
           preds.length === 0 ? <p className="text-sm text-muted-foreground">No picks for this filter.</p> :
           <div className="grid md:grid-cols-2 gap-4">{preds.map((p) => <PredictionCard key={p.id} p={p} />)}</div>}
        </div>
      )}
    </div>
  );
}
