import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { getAnalyses, getPredictions, updateAllPendingResults } from "@/lib/predictions.functions";
import { useState, useMemo } from "react";
import { ChevronDown, ChevronRight, Loader2, RefreshCw, Search } from "lucide-react";
import { PredictionCard, type Prediction } from "@/components/PredictionCard";
import { ScanScorecard } from "@/components/ScanScorecard";
import { LeagueScopeBadge } from "@/components/LeagueScopeBadge";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

export const Route = createFileRoute("/history")({
  head: () => ({
    meta: [
      { title: "Analysis History · BetEdge AI" },
      { name: "description", content: "Browse previous prediction scans with full reasoning, confidence trail and final-result tracking." },
      { property: "og:title", content: "Analysis History · BetEdge AI" },
      { property: "og:description", content: "Persistent record of every scan — update FT results without re-running predictions." },
      { property: "og:url", content: "/history" },
    ],
    links: [{ rel: "canonical", href: "/history" }],
  }),
  component: HistoryPage,
});

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
function formatScanLabel(iso: string): string {
  const d = new Date(iso);
  const dd = String(d.getDate()).padStart(2, "0");
  const mon = MONTHS[d.getMonth()];
  const yyyy = d.getFullYear();
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  return `${dd} ${mon} ${yyyy} · ${hh}:${mm}`;
}

// Scanner now only generates match_winner and over_1_5_goals — the two bet types with a
// real, measurable edge in this API's data. Older scans may still have picks of the
// removed types (corners, double chance, asian handicap); "All" will still show those if
// present in history, they just won't be generated by new scans.
const TYPE_FILTERS = [
  { id: "all", label: "All" },
  { id: "match_winner", label: "Match Winner" },
  { id: "over_1_5_goals", label: "Over 1.5" },
];

function HistoryPage() {
  const fa = useServerFn(getAnalyses);
  const fp = useServerFn(getPredictions);
  const updateAll = useServerFn(updateAllPendingResults);
  const qc = useQueryClient();
  const aQ = useQuery({ queryKey: ["analyses"], queryFn: () => fa() });
  const [openId, setOpenId] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");

  const updateMut = useMutation({
    mutationFn: () => {
      const v = typeof window !== "undefined" ? window.localStorage.getItem("betedge.apiKey") : null;
      const apiKey: 1 | 2 = v === "2" ? 2 : 1;
      return updateAll({ data: { apiKey } });
    },
    onSuccess: (r: any) => {
      const failedNote = r.failedDates ? ` (${r.failedDates} date${r.failedDates === 1 ? "" : "s"} couldn't be checked — see logs.)` : "";
      const msg = `Updated ${r.updated} result${r.updated === 1 ? "" : "s"} across ${r.dates} date${r.dates === 1 ? "" : "s"}. ${r.stillPending} match${r.stillPending === 1 ? "" : "es"} still pending.${failedNote}`;
      if (r.updated === 0) toast.warning(msg);
      else toast.success(msg);
      qc.invalidateQueries({ queryKey: ["preds"] });
    },
    onError: (e: any) => toast.error(e?.message ?? "Update failed"),
  });

  const list = useMemo(() => {
    const items = aQ.data?.analyses ?? [];
    if (!search) return items;
    const s = search.toLowerCase();
    return items.filter((a: any) =>
      (a.scan_date ?? "").includes(s) ||
      new Date(a.created_at).toLocaleString().toLowerCase().includes(s),
    );
  }, [aQ.data, search]);

  return (
    <section className="mx-auto max-w-7xl px-4 sm:px-6 py-10">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-3xl font-bold">Analysis <span className="text-neon">History</span></h1>
          <p className="text-sm text-muted-foreground mt-1">Persistent record of every scan. Update FT results without re-running predictions.</p>
        </div>
        <Button onClick={() => updateMut.mutate()} disabled={updateMut.isPending}>
          {updateMut.isPending ? <Loader2 className="animate-spin h-4 w-4" /> : <RefreshCw className="h-4 w-4" />}
          Update Results
        </Button>
      </div>

      <div className="mt-6 glass rounded-xl p-3 flex items-center gap-2">
        <Search className="h-4 w-4 text-muted-foreground ml-2" />
        <input
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          placeholder="Search by date (YYYY-MM-DD or formatted)…"
          aria-label="Search analyses"
          className="flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground py-2"
        />
      </div>

      <div className="mt-4 flex flex-wrap gap-1.5">
        {TYPE_FILTERS.map((f) => (
          <button key={f.id} onClick={() => setTypeFilter(f.id)}
            className={`px-3 h-8 rounded-md text-xs border ${typeFilter === f.id ? "bg-neon/15 border-neon/40 text-neon" : "border-border text-muted-foreground hover:text-foreground"}`}>
            {f.label}
          </button>
        ))}
      </div>

      <div className="mt-6 space-y-2">
        {aQ.isLoading && <p className="text-sm text-muted-foreground">Loading…</p>}
        {!aQ.isLoading && list.length === 0 && (
          <div className="glass rounded-xl p-10 text-center text-sm text-muted-foreground">No analyses yet.</div>
        )}
        {list.map((a: any) => (
          <HistoryItem
            key={a.id}
            a={a}
            open={openId === a.id}
            onToggle={() => setOpenId((o) => (o === a.id ? null : a.id))}
            fp={fp}
            typeFilter={typeFilter}
          />
        ))}
      </div>
    </section>
  );
}

function HistoryItem({ a, open, onToggle, fp, typeFilter }: any) {
  const q = useQuery({
    queryKey: ["preds", "analysis", a.id],
    queryFn: () => fp({ data: { analysisId: a.id } }),
    enabled: open,
  });
  const allPreds = (q.data?.predictions ?? []) as Prediction[];
  const preds = typeFilter === "all" ? allPreds : allPreds.filter((p) => p.prediction_type === typeFilter);
  return (
    <div className="glass rounded-xl">
      <button onClick={onToggle} className="w-full flex items-center gap-3 p-4 text-left">
        {open ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}
        <div className="flex-1 min-w-0">
          <div className="font-semibold">{formatScanLabel(a.created_at)}</div>
          <div className="text-xs text-muted-foreground">{a.predictions_generated} pick{a.predictions_generated === 1 ? "" : "s"} · {a.matches_analyzed} match{a.matches_analyzed === 1 ? "" : "es"} analysed</div>
        </div>
        <div className="flex items-center gap-3">
          <LeagueScopeBadge scope={a.league_scope} />
          <ScanScorecard total={a.score_total ?? a.predictions_generated ?? 0} won={a.score_won ?? 0} pending={a.score_pending ?? 0} />
          <div className="text-right">
            {a.avg_confidence != null && <div className="font-mono text-neon font-bold">{a.avg_confidence}%</div>}
          </div>
        </div>
      </button>
      {open && (
        <div className="border-t border-border p-4 space-y-4">
          <div className="text-xs text-muted-foreground">{preds.length} picks shown</div>
          {q.isLoading ? <p className="text-sm text-muted-foreground">Loading picks…</p> :
           preds.length === 0 ? <p className="text-sm text-muted-foreground">No picks for this filter.</p> :
           <div className="grid md:grid-cols-2 gap-4">{preds.map((p) => <PredictionCard key={p.id} p={p} />)}</div>}
        </div>
      )}
    </div>
  );
}
