import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,next){if(s.startsWith('./')&&!/\.[a-z]+$/.test(s))s+='.ts';return next(s,c);}});
const {parseGoalooAnalysis,matchSavedResult}=await import('../src/lib/goaloo-analysis.ts');
const {parseSchedule}=await import('../src/lib/goaloo-parser.ts');
const {parseGoalooOdds}=await import('../src/lib/goaloo-odds.ts');
const {predictMatchOutcomes}=await import('../src/lib/predictions.server.ts');
const ft=`<tr><th>FT</th></tr><tr><td>Total</td><td>20</td><td>10</td><td>4</td><td>6</td><td>30</td><td>20</td><td>34</td><td>3</td></tr><tr><td>Home Field</td><td>10</td><td>8</td><td>1</td><td>1</td><td>20</td><td>8</td><td>25</td><td>2</td></tr><tr><td>Away Field</td><td>10</td><td>2</td><td>3</td><td>5</td><td>10</td><td>12</td><td>9</td><td>6</td></tr><tr><th class='ht-desc'>HT</th></tr><tr><td>Home Field</td><td>100</td><td>100</td><td>0</td><td>0</td><td>300</td><td>0</td><td>300</td><td>1</td></tr>`;
const html=`<script type="application/ld+json">{"@type":"SportsEvent","startDate":"2099-10-08T12:00:00Z"}</script><script>var scheduleId = 123;var h2h_home = 1;var h2h_away = 2;state:parseInt('0')</script><table class='team-table-home'>${ft}</table><table class='team-table-guest'>${ft}</table><tr id="tr1_1" index="9" info="2,1,1,0,0"><td title="League">League</td><span data-t='2026-01-01 12:00:00'></span><a onclick="soccerDbPage.team(1)">Home</a><a onclick="soccerDbPage.team(3)">Other</a><span class="fcorner_1">6-3</span></tr>`;
const a=parseGoalooAnalysis(html,'123');
assert.equal(a.data.homeDataVs.home.count,10);assert.equal(a.data.homeDataVs.home.win,8);
assert.deepEqual(a.data.homeLastMatches[0].slice(14),['6','3']);
assert.ok(predictMatchOutcomes(a,'1','2').length);
assert.throws(()=>parseGoalooAnalysis(html,'456'));
assert.throws(()=>parseGoalooAnalysis(html.replace("parseInt('0')","parseInt('-1')"),'123'));
const body=JSON.stringify({ErrCode:0,Data:"var matchcount=1;B[1]=[1,'','League'];A[1]=[123,1,1,2,'Home','Away','2026,9,7,12,00,00',-1,2,1,0,0,0,0,0,0,'3','4','','',0,'','',6,3,0];"});
const f=parseSchedule(body)[0];assert.equal(f.kickoff,'2026-10-07T12:00:00.000Z');assert.equal(f.homeId,'1');assert.equal(f.raw[24],3);
assert.throws(()=>parseSchedule(body.replace('matchcount=1','matchcount=2')));
const mix=JSON.stringify({ErrCode:0,MatchState:0,Data:{mixodds:[{cn:'Book',cid:1,euro:{l:{u:2,g:3,d:4}},ou:{l:{u:.9,g:2.5,d:.8}},ah:{l:{u:.8,g:-.5,d:1}}}]}});
const q=parseGoalooOdds(mix,null,'2026-10-07');assert.equal(q.find(x=>x.market==='home').odds,2);assert.equal(q.find(x=>x.market==='total-over-2.5').odds,1.9);assert.equal(q.find(x=>x.market==='ah:home:0.5').odds,1.8);
assert.throws(()=>parseGoalooOdds(mix.replace('"MatchState":0','"MatchState":-1'),null,''));
const r={matchId:'goaloo:123',homeName:'Home',awayName:'Away',kickoff:f.kickoff};
assert.equal(matchSavedResult({match_id:'goaloo:123'},[r]),r);
assert.equal(matchSavedResult({match_id:'987',home_team:'Home',away_team:'Away',kickoff:f.kickoff},[r]),r);
assert.equal(matchSavedResult({match_id:'123',home_team:'Other',away_team:'Away',kickoff:f.kickoff},[r]),undefined);
assert.equal(matchSavedResult({match_id:'987',home_team:'Home',away_team:'Away',kickoff:f.kickoff},[r,r]),undefined);
console.log('Goaloo mapping, season FT splits, odds conversion, ID isolation and legacy result matching passed');
