/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CornersRouteImport } from './routes/corners'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAnalyzeStreamRouteImport } from './routes/api/analyze-stream'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CornersRoute = CornersRouteImport.update({
  id: '/corners',
  path: '/corners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeStreamRoute = ApiAnalyzeStreamRouteImport.update({
  id: '/api/analyze-stream',
  path: '/api/analyze-stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corners': typeof CornersRoute
  '/history': typeof HistoryRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corners': typeof CornersRoute
  '/history': typeof HistoryRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corners': typeof CornersRoute
  '/history': typeof HistoryRoute
  '/matches': typeof MatchesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corners'
    | '/history'
    | '/matches'
    | '/settings'
    | '/sitemap.xml'
    | '/api/analyze-stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corners'
    | '/history'
    | '/matches'
    | '/settings'
    | '/sitemap.xml'
    | '/api/analyze-stream'
  id:
    | '__root__'
    | '/'
    | '/corners'
    | '/history'
    | '/matches'
    | '/settings'
    | '/sitemap.xml'
    | '/api/analyze-stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CornersRoute: typeof CornersRoute
  HistoryRoute: typeof HistoryRoute
  MatchesRoute: typeof MatchesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnalyzeStreamRoute: typeof ApiAnalyzeStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corners': {
      id: '/corners'
      path: '/corners'
      fullPath: '/corners'
      preLoaderRoute: typeof CornersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-stream': {
      id: '/api/analyze-stream'
      path: '/api/analyze-stream'
      fullPath: '/api/analyze-stream'
      preLoaderRoute: typeof ApiAnalyzeStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CornersRoute: CornersRoute,
  HistoryRoute: HistoryRoute,
  MatchesRoute: MatchesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAnalyzeStreamRoute: ApiAnalyzeStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
