/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as ApiAnalyzeStreamRouteImport } from './routes/api/analyze-stream'
import { Route as ApiCronAutoScanRouteImport } from './routes/api/cron/auto-scan'
import { Route as ApiCronUpdateResultsRouteImport } from './routes/api/cron/update-results'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml', path: '/sitemap.xml', getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings', path: '/settings', getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history', path: '/history', getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/', path: '/', getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login', path: '/admin-login', getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeStreamRoute = ApiAnalyzeStreamRouteImport.update({
  id: '/api/analyze-stream', path: '/api/analyze-stream', getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutoScanRoute = ApiCronAutoScanRouteImport.update({
  id: '/api/cron/auto-scan', path: '/api/cron/auto-scan', getParentRoute: () => rootRouteImport,
} as any)
const ApiCronUpdateResultsRoute = ApiCronUpdateResultsRouteImport.update({
  id: '/api/cron/update-results', path: '/api/cron/update-results', getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/admin-login': typeof AdminLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
  '/api/cron/auto-scan': typeof ApiCronAutoScanRoute
  '/api/cron/update-results': typeof ApiCronUpdateResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/admin-login': typeof AdminLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
  '/api/cron/auto-scan': typeof ApiCronAutoScanRoute
  '/api/cron/update-results': typeof ApiCronUpdateResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/admin-login': typeof AdminLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/analyze-stream': typeof ApiAnalyzeStreamRoute
  '/api/cron/auto-scan': typeof ApiCronAutoScanRoute
  '/api/cron/update-results': typeof ApiCronUpdateResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/settings'
    | '/admin-login'
    | '/sitemap.xml'
    | '/api/analyze-stream'
    | '/api/cron/auto-scan'
    | '/api/cron/update-results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history' | '/settings' | '/admin-login' | '/sitemap.xml' | '/api/analyze-stream' | '/api/cron/auto-scan' | '/api/cron/update-results'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/settings'
    | '/admin-login'
    | '/sitemap.xml'
    | '/api/analyze-stream'
    | '/api/cron/auto-scan'
    | '/api/cron/update-results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnalyzeStreamRoute: typeof ApiAnalyzeStreamRoute
  ApiCronAutoScanRoute: typeof ApiCronAutoScanRoute
  ApiCronUpdateResultsRoute: typeof ApiCronUpdateResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'; path: '/sitemap.xml'; fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport; parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'; path: '/settings'; fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport; parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'; path: '/history'; fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport; parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'; path: '/'; fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'; path: '/admin-login'; fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport; parentRoute: typeof rootRouteImport
    }
    '/api/analyze-stream': {
      id: '/api/analyze-stream'; path: '/api/analyze-stream'; fullPath: '/api/analyze-stream'
      preLoaderRoute: typeof ApiAnalyzeStreamRouteImport; parentRoute: typeof rootRouteImport
    }
    '/api/cron/auto-scan': {
      id: '/api/cron/auto-scan'; path: '/api/cron/auto-scan'; fullPath: '/api/cron/auto-scan'
      preLoaderRoute: typeof ApiCronAutoScanRouteImport; parentRoute: typeof rootRouteImport
    }
    '/api/cron/update-results': {
      id: '/api/cron/update-results'; path: '/api/cron/update-results'; fullPath: '/api/cron/update-results'
      preLoaderRoute: typeof ApiCronUpdateResultsRouteImport; parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  HistoryRoute,
  SettingsRoute,
  AdminLoginRoute,
  SitemapDotxmlRoute,
  ApiAnalyzeStreamRoute,
  ApiCronAutoScanRoute,
  ApiCronUpdateResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
